---
name: CI
"on":
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - run: pip install poetry
      - run: poetry install

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - run: npm install
      - run: poetry run make -j $(nproc)
